"""Seed worldwide airport, airline, and route reference data into the database."""

import asyncio
import sys
from pathlib import Path

# Add backend to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / "backend"))

import airportsdata
from sqlalchemy import select, delete
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.config import settings, DB_PATH
from app.models.base import Base
from app.models.airport import Airport
from app.models.airline import Airline
from app.models.route import Route

# ──────────────────────────────────────────────
# Korean city name mappings for major cities
# ──────────────────────────────────────────────
CITY_KO_MAP: dict[str, str] = {
    # 한국
    "Seoul": "서울",
    "Busan": "부산",
    "Jeju": "제주",
    "Daegu": "대구",
    "Gwangju": "광주",
    "Cheongju": "청주",
    "Muan": "무안",
    "Yangyang": "양양",
    "Gunsan": "군산",
    "Pohang": "포항",
    "Sacheon": "사천",
    "Wonju": "원주",
    "Yeosu": "여수",
    "Ulsan": "울산",
    # 일본
    "Tokyo": "도쿄",
    "Osaka": "오사카",
    "Nagoya": "나고야",
    "Fukuoka": "후쿠오카",
    "Sapporo": "삿포로",
    "Okinawa": "오키나와",
    "Naha": "나하",
    "Kyoto": "교토",
    "Kobe": "고베",
    "Hiroshima": "히로시마",
    "Sendai": "센다이",
    "Kagoshima": "가고시마",
    "Kumamoto": "구마모토",
    "Nagasaki": "나가사키",
    "Kitakyushu": "기타큐슈",
    "Matsuyama": "마쓰야마",
    "Takamatsu": "다카마쓰",
    "Niigata": "니가타",
    "Toyama": "도야마",
    "Komatsu": "고마쓰",
    "Okayama": "오카야마",
    "Oita": "오이타",
    "Miyazaki": "미야자키",
    "Asahikawa": "아사히카와",
    "Hakodate": "하코다테",
    "Obihiro": "오비히로",
    "Kushiro": "구시로",
    "Ishigaki": "이시가키",
    "Miyako": "미야코",
    "Shizuoka": "시즈오카",
    "Aomori": "아오모리",
    "Akita": "아키타",
    # 중국
    "Beijing": "베이징",
    "Shanghai": "상하이",
    "Guangzhou": "광저우",
    "Shenzhen": "선전",
    "Chengdu": "청두",
    "Hangzhou": "항저우",
    "Wuhan": "우한",
    "Chongqing": "충칭",
    "Xi'an": "시안",
    "Nanjing": "난징",
    "Tianjin": "톈진",
    "Qingdao": "칭다오",
    "Dalian": "다롄",
    "Xiamen": "샤먼",
    "Kunming": "쿤밍",
    "Harbin": "하얼빈",
    "Shenyang": "선양",
    "Changsha": "창사",
    "Zhengzhou": "정저우",
    "Haikou": "하이커우",
    "Sanya": "싼야",
    "Guilin": "구이린",
    "Suzhou": "쑤저우",
    "Fuzhou": "푸저우",
    "Jinan": "지난",
    "Changchun": "창춘",
    "Wenzhou": "원저우",
    "Guiyang": "구이양",
    "Nanning": "난닝",
    "Lanzhou": "란저우",
    "Urumqi": "우루무치",
    "Hohhot": "후허하오터",
    "Yinchuan": "인촨",
    "Lhasa": "라싸",
    # 대만
    "Taipei": "타이베이",
    "Kaohsiung": "가오슝",
    "Taichung": "타이중",
    "Tainan": "타이난",
    "Hualien": "화롄",
    # 홍콩/마카오
    "Hong Kong": "홍콩",
    "Macau": "마카오",
    "Macao": "마카오",
    # 동남아시아
    "Bangkok": "방콕",
    "Singapore": "싱가포르",
    "Kuala Lumpur": "쿠알라룸푸르",
    "Ho Chi Minh City": "호치민",
    "Hanoi": "하노이",
    "Da Nang": "다낭",
    "Nha Trang": "나트랑",
    "Phu Quoc": "푸꾸옥",
    "Manila": "마닐라",
    "Cebu": "세부",
    "Jakarta": "자카르타",
    "Bali": "발리",
    "Denpasar": "덴파사르",
    "Phnom Penh": "프놈펜",
    "Siem Reap": "시엠립",
    "Vientiane": "비엔티안",
    "Luang Prabang": "루앙프라방",
    "Yangon": "양곤",
    "Chiang Mai": "치앙마이",
    "Chiang Rai": "치앙라이",
    "Phuket": "푸켓",
    "Krabi": "끄라비",
    "Koh Samui": "코사무이",
    "Pattaya": "파타야",
    "Boracay": "보라카이",
    "Yogyakarta": "족자카르타",
    "Surabaya": "수라바야",
    "Bandung": "반둥",
    "Penang": "페낭",
    "Langkawi": "랑카위",
    "Kota Kinabalu": "코타키나발루",
    "Brunei": "브루나이",
    # 남아시아
    "New Delhi": "뉴델리",
    "Delhi": "델리",
    "Mumbai": "뭄바이",
    "Bangalore": "방갈로르",
    "Chennai": "첸나이",
    "Kolkata": "콜카타",
    "Hyderabad": "하이데라바드",
    "Kathmandu": "카트만두",
    "Colombo": "콜롬보",
    "Dhaka": "다카",
    "Male": "말레",
    # 중동
    "Dubai": "두바이",
    "Abu Dhabi": "아부다비",
    "Doha": "도하",
    "Riyadh": "리야드",
    "Jeddah": "제다",
    "Istanbul": "이스탄불",
    "Ankara": "앙카라",
    "Tel Aviv": "텔아비브",
    "Amman": "암만",
    "Beirut": "베이루트",
    "Kuwait City": "쿠웨이트",
    "Muscat": "무스카트",
    "Bahrain": "바레인",
    "Tehran": "테헤란",
    "Baghdad": "바그다드",
    # 미국/캐나다
    "Los Angeles": "로스앤젤레스",
    "New York": "뉴욕",
    "San Francisco": "샌프란시스코",
    "Chicago": "시카고",
    "Las Vegas": "라스베이거스",
    "Honolulu": "호놀룰루",
    "Seattle": "시애틀",
    "Washington": "워싱턴",
    "Boston": "보스턴",
    "Dallas": "댈러스",
    "Houston": "휴스턴",
    "Atlanta": "애틀랜타",
    "Miami": "마이애미",
    "Denver": "덴버",
    "Phoenix": "피닉스",
    "San Diego": "샌디에이고",
    "Orlando": "올랜도",
    "Philadelphia": "필라델피아",
    "Minneapolis": "미니애폴리스",
    "Detroit": "디트로이트",
    "Portland": "포틀랜드",
    "San Jose": "산호세",
    "Austin": "오스틴",
    "Nashville": "내슈빌",
    "Salt Lake City": "솔트레이크시티",
    "Charlotte": "샬럿",
    "Pittsburgh": "피츠버그",
    "Tampa": "탬파",
    "Anchorage": "앵커리지",
    "Toronto": "토론토",
    "Vancouver": "밴쿠버",
    "Montreal": "몬트리올",
    "Calgary": "캘거리",
    "Ottawa": "오타와",
    # 유럽
    "London": "런던",
    "Paris": "파리",
    "Frankfurt": "프랑크푸르트",
    "Amsterdam": "암스테르담",
    "Rome": "로마",
    "Milan": "밀라노",
    "Madrid": "마드리드",
    "Barcelona": "바르셀로나",
    "Munich": "뮌헨",
    "Berlin": "베를린",
    "Zurich": "취리히",
    "Vienna": "비엔나",
    "Prague": "프라하",
    "Budapest": "부다페스트",
    "Warsaw": "바르샤바",
    "Stockholm": "스톡홀름",
    "Copenhagen": "코펜하겐",
    "Oslo": "오슬로",
    "Helsinki": "헬싱키",
    "Dublin": "더블린",
    "Edinburgh": "에든버러",
    "Manchester": "맨체스터",
    "Brussels": "브뤼셀",
    "Lisbon": "리스본",
    "Athens": "아테네",
    "Moscow": "모스크바",
    "Saint Petersburg": "상트페테르부르크",
    "Reykjavik": "레이캬비크",
    "Venice": "베네치아",
    "Florence": "피렌체",
    "Naples": "나폴리",
    "Nice": "니스",
    "Lyon": "리옹",
    "Marseille": "마르세유",
    "Hamburg": "함부르크",
    "Dusseldorf": "뒤셀도르프",
    "Cologne": "쾰른",
    "Geneva": "제네바",
    "Salzburg": "잘츠부르크",
    "Krakow": "크라쿠프",
    "Dubrovnik": "두브로브니크",
    "Split": "스플리트",
    "Zagreb": "자그레브",
    "Ljubljana": "류블랴나",
    "Bucharest": "부쿠레슈티",
    "Sofia": "소피아",
    "Belgrade": "베오그라드",
    "Tallinn": "탈린",
    "Riga": "리가",
    "Vilnius": "빌뉴스",
    "Santorini": "산토리니",
    "Mykonos": "미코노스",
    "Porto": "포르투",
    "Seville": "세비야",
    "Malaga": "말라가",
    "Ibiza": "이비자",
    "Palma de Mallorca": "팔마데마요르카",
    # 오세아니아
    "Sydney": "시드니",
    "Melbourne": "멜버른",
    "Brisbane": "브리즈번",
    "Perth": "퍼스",
    "Auckland": "오클랜드",
    "Wellington": "웰링턴",
    "Queenstown": "퀸스타운",
    "Christchurch": "크라이스트처치",
    "Gold Coast": "골드코스트",
    "Cairns": "케언즈",
    "Adelaide": "애들레이드",
    "Hobart": "호바트",
    "Darwin": "다윈",
    "Fiji": "피지",
    "Nadi": "나디",
    "Guam": "괌",
    "Saipan": "사이판",
    "Palau": "팔라우",
    # 아프리카
    "Cairo": "카이로",
    "Johannesburg": "요하네스버그",
    "Cape Town": "케이프타운",
    "Nairobi": "나이로비",
    "Casablanca": "카사블랑카",
    "Marrakech": "마라케시",
    "Lagos": "라고스",
    "Addis Ababa": "아디스아바바",
    "Dar es Salaam": "다르에스살람",
    "Accra": "아크라",
    "Tunis": "튀니스",
    "Algiers": "알제",
    # 중남미
    "Cancun": "칸쿤",
    "Mexico City": "멕시코시티",
    "Sao Paulo": "상파울루",
    "Rio de Janeiro": "리우데자네이루",
    "Buenos Aires": "부에노스아이레스",
    "Lima": "리마",
    "Bogota": "보고타",
    "Santiago": "산티아고",
    "Havana": "아바나",
    "San Juan": "산후안",
    "Panama City": "파나마시티",
    "Quito": "키토",
    "Montevideo": "몬테비데오",
    "Cartagena": "카르타헤나",
    "Cusco": "쿠스코",
}

# Additional IATA-specific Korean name overrides (for airports where city name doesn't match well)
IATA_KO_OVERRIDE: dict[str, str] = {
    "ICN": "서울/인천",
    "GMP": "서울/김포",
    "NRT": "도쿄/나리타",
    "HND": "도쿄/하네다",
    "KIX": "오사카/간사이",
    "ITM": "오사카/이타미",
    "NGO": "나고야/주부",
    "CTS": "삿포로/치토세",
    "FUK": "후쿠오카",
    "OKA": "오키나와/나하",
    "PEK": "베이징/수도",
    "PKX": "베이징/다싱",
    "PVG": "상하이/푸둥",
    "SHA": "상하이/훙차오",
    "CAN": "광저우/바이윈",
    "SZX": "선전/바오안",
    "TPE": "타이베이/타오위안",
    "TSA": "타이베이/쑹산",
    "KHH": "가오슝",
    "DXB": "두바이",
    "AUH": "아부다비",
    "DOH": "도하/하마드",
    "IST": "이스탄불",
    "SAW": "이스탄불/사비하",
    "LHR": "런던/히드로",
    "LGW": "런던/개트윅",
    "STN": "런던/스탠스테드",
    "LTN": "런던/루턴",
    "LCY": "런던시티",
    "CDG": "파리/샤를드골",
    "ORY": "파리/오를리",
    "FRA": "프랑크푸르트",
    "MUC": "뮌헨",
    "AMS": "암스테르담/스키폴",
    "FCO": "로마/피우미치노",
    "CIA": "로마/치암피노",
    "MXP": "밀라노/말펜사",
    "LIN": "밀라노/리나테",
    "MAD": "마드리드/바라하스",
    "BCN": "바르셀로나",
    "JFK": "뉴욕/JFK",
    "EWR": "뉴욕/뉴어크",
    "LGA": "뉴욕/라과디아",
    "LAX": "로스앤젤레스",
    "SFO": "샌프란시스코",
    "ORD": "시카고/오헤어",
    "MDW": "시카고/미드웨이",
    "IAD": "워싱턴/덜레스",
    "DCA": "워싱턴/레이건",
    "ATL": "애틀랜타",
    "DFW": "댈러스/포트워스",
    "MIA": "마이애미",
    "SEA": "시애틀/타코마",
    "BOS": "보스턴",
    "DEN": "덴버",
    "LAS": "라스베이거스",
    "HNL": "호놀룰루",
    "SYD": "시드니",
    "MEL": "멜버른",
    "BNE": "브리즈번",
    "AKL": "오클랜드",
    "GUM": "괌",
    "SPN": "사이판",
    "CJU": "제주",
    "PUS": "부산/김해",
    "TAE": "대구",
    "CJJ": "청주",
    "KWJ": "광주",
    "MWX": "무안",
    "RSU": "여수",
    "USN": "울산",
    "WJU": "원주",
    "HIN": "사천",
    "KPO": "포항",
    "YNY": "양양",
    "YVR": "밴쿠버",
    "YYZ": "토론토/피어슨",
    "YUL": "몬트리올",
    "GIG": "리우데자네이루/갈레앙",
    "GRU": "상파울루/과룰류스",
    "EZE": "부에노스아이레스/에세이사",
    "NAN": "나디/피지",
    "ROR": "팔라우/코로르",
    "DAD": "다낭",
    "SGN": "호치민/떤선녓",
    "HAN": "하노이/노이바이",
    "CXR": "나트랑/깜라인",
    "PQC": "푸꾸옥",
    "REP": "시엠립",
    "PNH": "프놈펜",
    "RGN": "양곤",
    "CNX": "치앙마이",
    "HKT": "푸켓",
    "KBV": "끄라비",
    "USM": "코사무이",
    "CEB": "세부/막탄",
    "MNL": "마닐라/니노이아키노",
    "DPS": "발리/응우라라이",
    "CGK": "자카르타/수카르노하타",
    "KUL": "쿠알라룸푸르",
    "BKI": "코타키나발루",
    "LGK": "랑카위",
    "PEN": "페낭",
    "SIN": "싱가포르/창이",
    "DEL": "뉴델리/인디라간디",
    "BOM": "뭄바이",
    "BLR": "방갈로르",
    "MLE": "말레/몰디브",
    "CMB": "콜롬보",
    "CAI": "카이로",
    "JNB": "요하네스버그",
    "CPT": "케이프타운",
    "NBO": "나이로비",
    "CMN": "카사블랑카",
    "RAK": "마라케시",
    "CUN": "칸쿤",
    "MEX": "멕시코시티",
    "SCL": "산티아고",
    "LIM": "리마",
    "BOG": "보고타",
    "HAV": "아바나",
    "PTY": "파나마시티",
    "ZRH": "취리히",
    "VIE": "비엔나",
    "PRG": "프라하",
    "BUD": "부다페스트",
    "WAW": "바르샤바",
    "ARN": "스톡홀름/알란다",
    "CPH": "코펜하겐",
    "OSL": "오슬로",
    "HEL": "헬싱키",
    "DUB": "더블린",
    "BRU": "브뤼셀",
    "LIS": "리스본",
    "ATH": "아테네",
    "SVO": "모스크바/셰레메티예보",
    "DME": "모스크바/도모데도보",
    "LED": "상트페테르부르크",
    "KEF": "레이캬비크",
    "VCE": "베네치아",
    "FLR": "피렌체",
    "NAP": "나폴리",
    "NCE": "니스",
    "HAM": "함부르크",
    "DUS": "뒤셀도르프",
    "CGN": "쾰른/본",
    "GVA": "제네바",
    "SZG": "잘츠부르크",
    "DBV": "두브로브니크",
    "JTR": "산토리니",
    "MYK": "미코노스",
    "OPO": "포르투",
    "IBZ": "이비자",
    "PMI": "팔마데마요르카",
    "TXL": "베를린/테겔",
    "BER": "베를린/브란덴부르크",
    "MAN": "맨체스터",
    "EDI": "에든버러",
}

# Major airlines
AIRLINES = [
    ("KE", "Korean Air", "KR"),
    ("OZ", "Asiana Airlines", "KR"),
    ("7C", "Jeju Air", "KR"),
    ("TW", "T'way Air", "KR"),
    ("LJ", "Jin Air", "KR"),
    ("BX", "Air Busan", "KR"),
    ("RS", "Air Seoul", "KR"),
    ("ZE", "Eastar Jet", "KR"),
    ("4V", "Fly Gangwon", "KR"),
    ("RF", "Aero K", "KR"),
    ("JL", "Japan Airlines", "JP"),
    ("NH", "All Nippon Airways", "JP"),
    ("MM", "Peach Aviation", "JP"),
    ("JW", "Vanilla Air", "JP"),
    ("BC", "Skymark Airlines", "JP"),
    ("GK", "Jetstar Japan", "JP"),
    ("CA", "Air China", "CN"),
    ("MU", "China Eastern Airlines", "CN"),
    ("CZ", "China Southern Airlines", "CN"),
    ("HU", "Hainan Airlines", "CN"),
    ("3U", "Sichuan Airlines", "CN"),
    ("SC", "Shandong Airlines", "CN"),
    ("ZH", "Shenzhen Airlines", "CN"),
    ("FM", "Shanghai Airlines", "CN"),
    ("CX", "Cathay Pacific", "HK"),
    ("HX", "Hong Kong Airlines", "HK"),
    ("CI", "China Airlines", "TW"),
    ("BR", "EVA Air", "TW"),
    ("IT", "Tigerair Taiwan", "TW"),
    ("TG", "Thai Airways", "TH"),
    ("FD", "Thai AirAsia", "TH"),
    ("SQ", "Singapore Airlines", "SG"),
    ("TR", "Scoot", "SG"),
    ("MI", "SilkAir", "SG"),
    ("MH", "Malaysia Airlines", "MY"),
    ("AK", "AirAsia", "MY"),
    ("D7", "AirAsia X", "MY"),
    ("VN", "Vietnam Airlines", "VN"),
    ("VJ", "VietJet Air", "VN"),
    ("QH", "Bamboo Airways", "VN"),
    ("PR", "Philippine Airlines", "PH"),
    ("5J", "Cebu Pacific", "PH"),
    ("GA", "Garuda Indonesia", "ID"),
    ("QZ", "Indonesia AirAsia", "ID"),
    ("AA", "American Airlines", "US"),
    ("UA", "United Airlines", "US"),
    ("DL", "Delta Air Lines", "US"),
    ("WN", "Southwest Airlines", "US"),
    ("B6", "JetBlue Airways", "US"),
    ("AS", "Alaska Airlines", "US"),
    ("HA", "Hawaiian Airlines", "US"),
    ("NK", "Spirit Airlines", "US"),
    ("BA", "British Airways", "GB"),
    ("AF", "Air France", "FR"),
    ("LH", "Lufthansa", "DE"),
    ("KL", "KLM Royal Dutch Airlines", "NL"),
    ("IB", "Iberia", "ES"),
    ("AZ", "ITA Airways", "IT"),
    ("LX", "Swiss International Air Lines", "CH"),
    ("OS", "Austrian Airlines", "AT"),
    ("SK", "Scandinavian Airlines", "SE"),
    ("AY", "Finnair", "FI"),
    ("EI", "Aer Lingus", "IE"),
    ("TP", "TAP Air Portugal", "PT"),
    ("TK", "Turkish Airlines", "TR"),
    ("EK", "Emirates", "AE"),
    ("QR", "Qatar Airways", "QA"),
    ("EY", "Etihad Airways", "AE"),
    ("SV", "Saudi Arabian Airlines", "SA"),
    ("WY", "Oman Air", "OM"),
    ("GF", "Gulf Air", "BH"),
    ("AC", "Air Canada", "CA"),
    ("WS", "WestJet", "CA"),
    ("QF", "Qantas", "AU"),
    ("JQ", "Jetstar Airways", "AU"),
    ("NZ", "Air New Zealand", "NZ"),
    ("ET", "Ethiopian Airlines", "ET"),
    ("SA", "South African Airways", "ZA"),
    ("MS", "EgyptAir", "EG"),
    ("AT", "Royal Air Maroc", "MA"),
    ("AM", "Aeromexico", "MX"),
    ("LA", "LATAM Airlines", "CL"),
    ("AV", "Avianca", "CO"),
    ("CM", "Copa Airlines", "PA"),
    ("AI", "Air India", "IN"),
    ("6E", "IndiGo", "IN"),
    ("SG", "SpiceJet", "IN"),
    ("UL", "SriLankan Airlines", "LK"),
    ("RA", "Nepal Airlines", "NP"),
    ("FR", "Ryanair", "IE"),
    ("U2", "easyJet", "GB"),
    ("W6", "Wizz Air", "HU"),
    ("VY", "Vueling", "ES"),
    ("PC", "Pegasus Airlines", "TR"),
]

# Popular routes to seed
POPULAR_ROUTES = [
    # From ICN
    ("ICN", "NRT"), ("ICN", "KIX"), ("ICN", "HND"), ("ICN", "FUK"),
    ("ICN", "CTS"), ("ICN", "NGO"), ("ICN", "OKA"),
    ("ICN", "PVG"), ("ICN", "PEK"), ("ICN", "CAN"),
    ("ICN", "HKG"), ("ICN", "TPE"),
    ("ICN", "BKK"), ("ICN", "SIN"), ("ICN", "SGN"), ("ICN", "DAD"),
    ("ICN", "HAN"), ("ICN", "CEB"), ("ICN", "MNL"), ("ICN", "DPS"),
    ("ICN", "KUL"), ("ICN", "CNX"), ("ICN", "HKT"),
    ("ICN", "LAX"), ("ICN", "JFK"), ("ICN", "SFO"), ("ICN", "SEA"),
    ("ICN", "HNL"), ("ICN", "GUM"),
    ("ICN", "LHR"), ("ICN", "CDG"), ("ICN", "FRA"), ("ICN", "AMS"),
    ("ICN", "FCO"), ("ICN", "MAD"), ("ICN", "IST"),
    ("ICN", "DXB"), ("ICN", "DOH"),
    ("ICN", "SYD"), ("ICN", "AKL"),
    # From GMP
    ("GMP", "HND"), ("GMP", "KIX"), ("GMP", "CJU"),
    ("GMP", "PUS"), ("GMP", "TAE"), ("GMP", "CJJ"),
    # From PUS
    ("PUS", "NRT"), ("PUS", "KIX"), ("PUS", "FUK"),
    ("PUS", "PVG"), ("PUS", "TPE"), ("PUS", "BKK"),
    ("PUS", "DAD"), ("PUS", "SGN"), ("PUS", "CEB"),
    # From CJU
    ("CJU", "NRT"), ("CJU", "KIX"),
]


def get_korean_name(iata: str, city: str) -> str | None:
    """Get Korean name for an airport. Priority: IATA override > city map > None."""
    if iata in IATA_KO_OVERRIDE:
        return IATA_KO_OVERRIDE[iata]
    if city in CITY_KO_MAP:
        return CITY_KO_MAP[city]
    return None


async def seed() -> None:
    """Seed worldwide airports, airlines, and routes."""
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)

    engine = create_async_engine(settings.DATABASE_URL, echo=False)

    # Create tables
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    session_factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with session_factory() as session:
        # Clear existing data for re-seed
        await session.execute(delete(Route))
        await session.execute(delete(Airline))
        await session.execute(delete(Airport))
        await session.commit()

        # Load worldwide airport data
        airports_data = airportsdata.load("IATA")
        airport_count = 0

        for iata, info in airports_data.items():
            if not iata or len(iata) != 3:
                continue

            city = info.get("city", "")
            country = info.get("country", "")
            if len(country) > 2:
                country = country[:2]

            ko_name = get_korean_name(iata, city)

            session.add(Airport(
                iata_code=iata,
                name=info.get("name", ""),
                city=city,
                city_ko=ko_name,
                country_code=country,
                latitude=info.get("lat"),
                longitude=info.get("lon"),
                timezone=info.get("tz"),
            ))
            airport_count += 1

        # Seed airlines
        for iata, name, country in AIRLINES:
            session.add(Airline(iata_code=iata, name=name, country_code=country))

        await session.flush()

        # Seed routes
        for origin, dest in POPULAR_ROUTES:
            session.add(Route(origin_code=origin, dest_code=dest))

        await session.commit()

    await engine.dispose()
    print(f"Seeded {airport_count} airports, {len(AIRLINES)} airlines, {len(POPULAR_ROUTES)} routes")


if __name__ == "__main__":
    asyncio.run(seed())
